### ISSUE TITLE
Realizar procedimiento de instalación

### ISSUE THREAD

**Issue by fernandouval** [datauy/ReportaCiudad#5]

**Comment by fernandouval** [comment]
Se deja documentación de instalación: https://github.com/datauy/ReportaCiudad/wiki/Instalaci%C3%B3n-Reporta-Ciudad
Se espera la carga de imágenes y testing de sitio para pasar a revisión.

**Comment by guillecro** [comment]
Excelente, esto puede servir para poder hacer mejor el seguimiento :)
